version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_online_store
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - online-store

volumes:
  postgres_data:
    driver: local

networks:
  online-store: