version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_online_store
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - online-store

  api:
    build: .
    container_name: nest_api
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - online-store
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  online-store: