import { Prisma } from '@prisma/client'
import { hash } from 'argon2'

export async function getUsers(): Promise<Prisma.UserCreateInput[]> {
  return Promise.all([
    {
      email: 'alice@example.com',
      firstName: 'Alice',
      lastName: 'Johnson',
      password: await hash('password123'),
      phone: '+380501111111',
      address: 'Kyiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'bob@example.com',
      firstName: 'Bob',
      lastName: 'Smith',
      password: await hash('password123'),
      phone: '+380502222222',
      address: 'Lviv, Ukraine',
      role: 'ADMIN',
    },
    {
      email: 'carol@example.com',
      firstName: 'Carol',
      lastName: 'Novak',
      password: await hash('password123'),
      phone: '+380503333333',
      address: 'Odesa, Ukraine',
      role: 'USER',
    },
    {
      email: 'dave@example.com',
      firstName: 'Dave',
      lastName: 'Miller',
      password: await hash('password123'),
      phone: '+380504444444',
      address: 'Dnipro, Ukraine',
      role: 'USER',
    },
    {
      email: 'eve@example.com',
      firstName: 'Eve',
      lastName: 'Watson',
      password: await hash('password123'),
      phone: '+380505555555',
      address: 'Kharkiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'frank@example.com',
      firstName: 'Frank',
      lastName: 'Bauer',
      password: await hash('password123'),
      phone: '+380506666666',
      address: 'Zaporizhzhia, Ukraine',
      role: 'ADMIN',
    },
    {
      email: 'grace@example.com',
      firstName: 'Grace',
      lastName: 'Adams',
      password: await hash('password123'),
      phone: '+380507777777',
      address: 'Vinnytsia, Ukraine',
      role: 'USER',
    },
    {
      email: 'hank@example.com',
      firstName: 'Hank',
      lastName: 'Green',
      password: await hash('password123'),
      phone: '+380508888888',
      address: 'Chernihiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'irene@example.com',
      firstName: 'Irene',
      lastName: 'Kovalenko',
      password: await hash('password123'),
      phone: '+380509999999',
      address: 'Poltava, Ukraine',
      role: 'USER',
    },
    {
      email: 'jack@example.com',
      firstName: 'Jack',
      lastName: 'Black',
      password: await hash('password123'),
      phone: '+380501234567',
      address: 'Ternopil, Ukraine',
      role: 'USER',
    },
    {
      email: 'kate@example.com',
      firstName: 'Kate',
      lastName: 'Bush',
      password: await hash('password123'),
      phone: '+380502345678',
      address: 'Uzhhorod, Ukraine',
      role: 'USER',
    },
    {
      email: 'leo@example.com',
      firstName: 'Leo',
      lastName: 'Messi',
      password: await hash('password123'),
      phone: '+380503456789',
      address: 'Ivano-Frankivsk, Ukraine',
      role: 'USER',
    },
    {
      email: 'maya@example.com',
      firstName: 'Maya',
      lastName: 'Danyliuk',
      password: await hash('password123'),
      phone: '+380504567890',
      address: 'Kherson, Ukraine',
      role: 'USER',
    },
    {
      email: 'nate@example.com',
      firstName: 'Nate',
      lastName: 'Diaz',
      password: await hash('password123'),
      phone: '+380505678901',
      address: 'Mykolaiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'olga@example.com',
      firstName: 'Olga',
      lastName: 'Petrenko',
      password: await hash('password123'),
      phone: '+380506789012',
      address: 'Cherkasy, Ukraine',
      role: 'USER',
    },
    {
      email: 'peter@example.com',
      firstName: 'Peter',
      lastName: 'Parker',
      password: await hash('password123'),
      phone: '+380507890123',
      address: 'Sumy, Ukraine',
      role: 'USER',
    },
    {
      email: 'quinn@example.com',
      firstName: 'Quinn',
      lastName: 'Tarasov',
      password: await hash('password123'),
      phone: '+380508901234',
      address: 'Rivne, Ukraine',
      role: 'USER',
    },
    {
      email: 'rose@example.com',
      firstName: 'Rose',
      lastName: 'Tyler',
      password: await hash('password123'),
      phone: '+380509012345',
      address: 'Zhytomyr, Ukraine',
      role: 'USER',
    },
    {
      email: 'sam@example.com',
      firstName: 'Sam',
      lastName: 'Fisher',
      password: await hash('password123'),
      phone: '+380501112233',
      address: 'Lutsk, Ukraine',
      role: 'USER',
    },
    {
      email: 'tina@example.com',
      firstName: 'Tina',
      lastName: 'Karol',
      password: await hash('password123'),
      phone: '+380502223344',
      address: 'Kyiv, Ukraine',
      role: 'USER',
    },
  ])
}
