import { Prisma } from '@prisma/client'
import { hash } from 'argon2'

export async function getUsers(): Promise<Prisma.UserCreateInput[]> {
  return Promise.all([
    {
      email: 'alice@example.com',
      name: 'Alice Johnson',
      password: await hash('password123'),
      phone: '+380501111111',
      address: 'Kyiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'bob@example.com',
      name: 'Bob Smith',
      password: await hash('password123'),
      phone: '+380502222222',
      address: 'Lviv, Ukraine',
      role: 'ADMIN',
    },
    {
      email: 'carol@example.com',
      name: 'Carol Novak',
      password: await hash('password123'),
      phone: '+380503333333',
      address: 'Odesa, Ukraine',
      role: 'USER',
    },
    {
      email: 'dave@example.com',
      name: 'Dave Miller',
      password: await hash('password123'),
      phone: '+380504444444',
      address: 'Dnipro, Ukraine',
      role: 'USER',
    },
    {
      email: 'eve@example.com',
      name: 'Eve Watson',
      password: await hash('password123'),
      phone: '+380505555555',
      address: 'Kharkiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'frank@example.com',
      name: 'Frank Bauer',
      password: await hash('password123'),
      phone: '+380506666666',
      address: 'Zaporizhzhia, Ukraine',
      role: 'ADMIN',
    },
    {
      email: 'grace@example.com',
      name: 'Grace Adams',
      password: await hash('password123'),
      phone: '+380507777777',
      address: 'Vinnytsia, Ukraine',
      role: 'USER',
    },
    {
      email: 'hank@example.com',
      name: 'Hank Green',
      password: await hash('password123'),
      phone: '+380508888888',
      address: 'Chernihiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'irene@example.com',
      name: 'Irene Kovalenko',
      password: await hash('password123'),
      phone: '+380509999999',
      address: 'Poltava, Ukraine',
      role: 'USER',
    },
    {
      email: 'jack@example.com',
      name: 'Jack Black',
      password: await hash('password123'),
      phone: '+380501234567',
      address: 'Ternopil, Ukraine',
      role: 'USER',
    },
    {
      email: 'kate@example.com',
      name: 'Kate Bush',
      password: await hash('password123'),
      phone: '+380502345678',
      address: 'Uzhhorod, Ukraine',
      role: 'USER',
    },
    {
      email: 'leo@example.com',
      name: 'Leo Messi',
      password: await hash('password123'),
      phone: '+380503456789',
      address: 'Ivano-Frankivsk, Ukraine',
      role: 'USER',
    },
    {
      email: 'maya@example.com',
      name: 'Maya Danyliuk',
      password: await hash('password123'),
      phone: '+380504567890',
      address: 'Kherson, Ukraine',
      role: 'USER',
    },
    {
      email: 'nate@example.com',
      name: 'Nate Diaz',
      password: await hash('password123'),
      phone: '+380505678901',
      address: 'Mykolaiv, Ukraine',
      role: 'USER',
    },
    {
      email: 'olga@example.com',
      name: 'Olga Petrenko',
      password: await hash('password123'),
      phone: '+380506789012',
      address: 'Cherkasy, Ukraine',
      role: 'USER',
    },
    {
      email: 'peter@example.com',
      name: 'Peter Parker',
      password: await hash('password123'),
      phone: '+380507890123',
      address: 'Sumy, Ukraine',
      role: 'USER',
    },
    {
      email: 'quinn@example.com',
      name: 'Quinn Tarasov',
      password: await hash('password123'),
      phone: '+380508901234',
      address: 'Rivne, Ukraine',
      role: 'USER',
    },
    {
      email: 'rose@example.com',
      name: 'Rose Tyler',
      password: await hash('password123'),
      phone: '+380509012345',
      address: 'Zhytomyr, Ukraine',
      role: 'USER',
    },
    {
      email: 'sam@example.com',
      name: 'Sam Fisher',
      password: await hash('password123'),
      phone: '+380501112233',
      address: 'Lutsk, Ukraine',
      role: 'USER',
    },
    {
      email: 'tina@example.com',
      name: 'Tina Karol',
      password: await hash('password123'),
      phone: '+380502223344',
      address: 'Kyiv, Ukraine',
      role: 'USER',
    },
  ])
}
